SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_ACCELERATION = 400
PLAYER_MAX_SPEED = 600
PLAYER_FRICTION = 0.98
PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3
POWERUP_LIFETIME = 5.0
POWERUP_CHANCE = 0.1
POWERUP_DURATION = 5.0
SHIELD_DURATION = 5.0
XP_ORB_LIFETIME = 10.0
XP_ORB_CHANCE = 0.5

SHOT_RADIUS = 5
